### ISSUE TITLE
OACMPDM1 misaligned torches

### ISSUE THREAD

**Issue by The-Gig** [NeonKnightOA/oacmpvol1#8]
I'm checking old "todo lists" from the forum against z_oacmp1v4_beta-220322.pk3.

OACMPDM1: These two torches are a bit misaligned, they do not touch the wall. They are those near to the personal teleporter, not those near to the portable health.
![shot0213](https://user-images.githubusercontent.com/23258514/161790542-fb3f048e-2175-4030-8223-6516f6b2c0a7.jpg)
![shot0214](https://user-images.githubusercontent.com/23258514/161790549-a7cbb277-e82e-45e4-ae4d-d33dae782264.jpg)
.

**Comment by NeonKnightOA** [comment]
This one's trivial. Taking care of it.

**Comment by NeonKnightOA** [comment]
Just checked the map. Apparently the .bsp file and the .map file differ, as in the .bsp file the torches are indeed unaligned... however in the .map file they aren't. I'll compile and see.

**Comment by The-Gig** [comment]
Wondering if other map-bsp may be "different" then. Maybe last modify date may give some hint? But it is possible that a .bsp has been compiled without its .map being modified that day...

**Comment by NeonKnightOA** [comment]
Yeah, that's what I'm checking.

**Comment by NeonKnightOA** [comment]
Fixed in oacmpvol1@c51ca2a

**Comment by The-Gig** [comment]
I tested the new version of the map, but I still see those two torches not touching the wall.. :-/

**Comment by The-Gig** [comment]
Uhm..  I tried it on another machine and it seems fixed. I have to find out whether I have a conflicting version of oacmpdm1 in one of my machines, then.

**Comment by The-Gig** [comment]
Closing.
